"""
CLIP-based AI image detector.

Uses openai/clip-vit-base-patch32 via the transformers library to score
whether an image looks AI-generated or authentic. This replaces the
72.4%-accuracy Random Forest heuristic model with a vision-language model
that generalises across diffusion fakes (DALL-E, Midjourney, Stable Diffusion)
and GAN fakes alike.

The model is loaded once at startup and cached. If it fails to load (no
internet, low memory) the module falls back gracefully so the rest of the
backend keeps working.
"""
from __future__ import annotations

import io
import logging
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Lazy model loading — only pulled from HuggingFace Hub on first use
# ---------------------------------------------------------------------------
_clip_processor: Any = None
_clip_model: Any = None
_clip_load_error: str | None = None
_clip_ready: bool = False

# Prompts that describe AI-generated vs real images.
# CLIP scores cosine similarity between the image and each text prompt.
_AI_PROMPTS = [
    "an AI generated image",
    "a deepfake photograph",
    "a synthetic face created by artificial intelligence",
    "a digitally manipulated image",
    "a fake image generated by a neural network",
    "a computer generated render",
]

_REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "an authentic unedited photo",
    "a genuine photograph of a real person",
    "a natural photograph with realistic lighting",
]


def _load_clip() -> None:
    global _clip_processor, _clip_model, _clip_load_error, _clip_ready
    if _clip_ready or _clip_load_error:
        return
    try:
        from transformers import CLIPModel, CLIPProcessor  # type: ignore
        logger.info("[CLIP] Loading openai/clip-vit-base-patch32 ...")
        _clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
        _clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
        _clip_model.eval()
        _clip_ready = True
        logger.info("[CLIP] Model loaded successfully.")
    except Exception as exc:
        _clip_load_error = str(exc)
        logger.warning("[CLIP] Could not load model: %s", exc)


@dataclass
class ClipAnalysisResult:
    available: bool
    ai_score: int          # 0-100, higher = more likely AI-generated
    real_score: int        # 0-100, higher = more likely authentic
    top_ai_prompt: str
    top_real_prompt: str
    error: str | None = None


def analyze_image_with_clip(image_bytes: bytes) -> ClipAnalysisResult:
    """
    Run CLIP zero-shot classification on image_bytes.
    Returns a ClipAnalysisResult with ai_score and real_score (0-100).
    Falls back gracefully if the model is unavailable.
    """
    _load_clip()

    if not _clip_ready:
        return ClipAnalysisResult(
            available=False,
            ai_score=0,
            real_score=0,
            top_ai_prompt="",
            top_real_prompt="",
            error=_clip_load_error or "CLIP model not available.",
        )

    try:
        import torch  # type: ignore
        from PIL import Image

        pil_image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        all_prompts = _AI_PROMPTS + _REAL_PROMPTS

        inputs = _clip_processor(
            text=all_prompts,
            images=pil_image,
            return_tensors="pt",
            padding=True,
        )

        with torch.no_grad():
            outputs = _clip_model(**inputs)
            # logits_per_image shape: [1, num_prompts]
            probs = outputs.logits_per_image.softmax(dim=1)[0].tolist()

        ai_probs = probs[: len(_AI_PROMPTS)]
        real_probs = probs[len(_AI_PROMPTS):]

        ai_total = sum(ai_probs)
        real_total = sum(real_probs)
        total = ai_total + real_total or 1.0

        ai_score = int(round(ai_total / total * 100))
        real_score = int(round(real_total / total * 100))

        top_ai_idx = ai_probs.index(max(ai_probs))
        top_real_idx = real_probs.index(max(real_probs))

        return ClipAnalysisResult(
            available=True,
            ai_score=min(max(ai_score, 0), 100),
            real_score=min(max(real_score, 0), 100),
            top_ai_prompt=_AI_PROMPTS[top_ai_idx],
            top_real_prompt=_REAL_PROMPTS[top_real_idx],
        )

    except Exception as exc:  # pragma: no cover
        logger.warning("[CLIP] Inference error: %s", exc)
        return ClipAnalysisResult(
            available=False,
            ai_score=0,
            real_score=0,
            top_ai_prompt="",
            top_real_prompt="",
            error=str(exc),
        )
